{{- if and .Values.enabled (not .Values.keyfile.existingSecret) }}
{{- $name := printf "%s-keyfile" (include "mongodb.fullname" .) -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
{{- $keyfile := .Values.keyfile.value -}}
{{- if and (not $keyfile) $existing $existing.data (hasKey $existing.data "keyfile") -}}
{{- $keyfile = (index $existing.data "keyfile" | b64dec) -}}
{{- else if not $keyfile -}}
{{- $keyfile = randAlphaNum 756 -}}
{{- end }}
# MongoDB Keyfile Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
stringData:
  keyfile: {{ $keyfile | quote }}
{{- end }}
