FROM nginx:1.27-alpine
ENV API_UPSTREAM=api:8080
ENV GRAFANA_UPSTREAM=grafana:3000
COPY web/docker-entrypoints.sh /docker-entrypoint.d/40-resolver.sh
COPY web/nginx.conf.template /etc/nginx/templates/default.conf.template
COPY web /usr/share/nginx/html
RUN sed -i -E 's|pid[[:space:]]+/run/nginx.pid;|pid        /tmp/nginx.pid;|; s|pid[[:space:]]+/var/run/nginx.pid;|pid        /tmp/nginx.pid;|' /etc/nginx/nginx.conf \
    && chmod 755 /docker-entrypoint.d/40-resolver.sh \
    && chmod 644 /etc/nginx/templates/default.conf.template \
    && chmod -R a+rX /usr/share/nginx/html \
    && chown -R nginx:nginx /var/cache/nginx /var/run /etc/nginx/conf.d /var/log/nginx
USER nginx
EXPOSE 8080
