{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "woms.fullname" . }}-prometheus
  labels:
    {{- include "woms.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "woms.fullname" . }}-prometheus
  labels:
    {{- include "woms.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
rules:
  - apiGroups: [""]
    resources: ["endpoints", "pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "woms.fullname" . }}-prometheus
  labels:
    {{- include "woms.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
subjects:
  - kind: ServiceAccount
    name: {{ include "woms.fullname" . }}-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "woms.fullname" . }}-prometheus
{{- end }}
