{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "woms.fullname" . }}-prometheus
  labels:
    {{- include "woms.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http
{{- end }}
