{{- if not .Values.api.jwtSecretExistingSecret }}
apiVersion: v1
kind: Secret
{{- $secretName := printf "%s-api" (include "woms.fullname" .) -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $jwtSecret := .Values.api.jwtSecret -}}
{{- if not $jwtSecret -}}
{{- if and $existing (hasKey $existing.data "JWT_SECRET") -}}
{{- $jwtSecret = (index $existing.data "JWT_SECRET" | b64dec) -}}
{{- else -}}
{{- $jwtSecret = randAlphaNum 64 -}}
{{- end -}}
{{- end }}
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "woms.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ $jwtSecret | quote }}
{{- end }}
