apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "woms.fullname" . }}-worker
  labels:
    {{- include "woms.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler-worker
spec:
  {{- if not .Values.keda.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: scheduler-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: scheduler-worker
    spec:
      containers:
        - name: scheduler-worker
          image: "{{ include "woms.image" (dict "registry" .Values.imageRegistry "repository" .Values.worker.image.repository "tag" .Values.worker.image.tag) }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: KAFKA_BROKERS
              value: {{ tpl .Values.keda.kafka.bootstrapServers . | quote }}
            - name: KAFKA_SCHEDULE_TOPIC
              value: {{ .Values.keda.kafka.topic | quote }}
            - name: KAFKA_CONSUMER_GROUP
              value: {{ .Values.keda.kafka.consumerGroup | quote }}
            - name: DATABASE_URL
              value: {{ .Values.worker.env.databaseUrl | quote }}
            - name: WORKER_MIN_JOB_DURATION_MS
              value: {{ .Values.worker.env.minJobDurationMs | quote }}
            - name: WORKER_MAX_RETRIES
              value: {{ .Values.worker.env.maxRetries | quote }}
            - name: WORKER_DEPENDENCY_RETRY_TIMEOUT_MS
              value: {{ .Values.worker.env.dependencyRetryTimeoutMs | quote }}
            - name: WORKER_DEPENDENCY_RETRY_INTERVAL_MS
              value: {{ .Values.worker.env.dependencyRetryIntervalMs | quote }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
